name: Continuous Integration Practice: Running Tests on push

on:
  push: # triggering event is a push to the repo
    branches:
      -ci-activity-6-branch # branch that this will be activated on

jobs:
  test: # job name
    runs-on: ubuntu-latest # VM image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      uses: pip install -r requirements.txt

    - name: Run Tests
      uses: pytest

